# Generated by Django 5.0.7 on 2025-05-07 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanCu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=5)),
                ('ma_can_cuoc', models.CharField(max_length=15)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('trang_thai', models.CharField(choices=[('Đang sinh sống', 'Đang sinh sống'), ('Đã chuyển đi', 'Đã chuyển đi'), ('Đã qua đời', 'Đã qua đời')], max_length=20)),
                ('thoi_gian_chuyen_den', models.DateField()),
                ('thoi_gian_chuyen_di', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DotThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dot_thu', models.CharField(max_length=150)),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('thoi_gian_bat_dau', models.DateField()),
                ('thoi_gian_ket_thuc', models.DateField()),
                ('trang_thai', models.CharField(choices=[('Đã hoàn thành', 'Đã hoàn thành'), ('Đang tiến hành', 'Đang tiến hành'), ('Chưa bắt đầu', 'Chưa bắt đầu')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KhoanThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khoan_thu', models.CharField(max_length=100)),
                ('loai_khoan_thu', models.CharField(choices=[('Bắt buộc', 'Bắt buộc'), ('Tự nguyện', 'Tự nguyện')], max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoGiaDinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_can_ho', models.IntegerField()),
                ('dien_tich', models.FloatField()),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('thoi_gian_bat_dau_o', models.DateField()),
                ('thoi_gian_ket_thuc_o', models.DateField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('Đang ở', 'Đang ở'), ('Đã rời đi', 'Đã rời đi')], max_length=20)),
                ('id_chu_ho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chu_ho', to='apartment_management.dancu')),
            ],
        ),
        migrations.AddField(
            model_name='dancu',
            name='ho_gia_dinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.hogiadinh'),
        ),
        migrations.CreateModel(
            name='ChiTietThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tien_can_nop', models.FloatField()),
                ('trang_thai_nop', models.CharField(choices=[('Đã nộp', 'Đã nộp'), ('chưa nộp', 'chưa nộp')], max_length=20)),
                ('ngay_nop', models.DateField(blank=True, null=True)),
                ('dot_thu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.dotthu')),
                ('ho_gia_dinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.hogiadinh')),
            ],
        ),
        migrations.AddField(
            model_name='dotthu',
            name='khoan_thu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.khoanthu'),
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_tro', models.CharField(choices=[('Quản trị hệ thống', 'Quản trị hệ thống'), ('BQL Chung cư', 'BQL Chung cư'), ('Kế toán', 'Kế toán')], max_length=50)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('trang_thai', models.CharField(choices=[('Đang hoạt động', 'Đang hoạt động'), ('Bị khóa', 'Bị khóa')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhuongTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_phuong_tien', models.CharField(choices=[('Ô tô', 'Ô tô'), ('Xe máy', 'Xe máy'), ('Xe đạp', 'Xe đạp')], max_length=20)),
                ('bien_so', models.CharField(max_length=255)),
                ('mau', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ho_gia_dinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.hogiadinh')),
            ],
        ),
        migrations.CreateModel(
            name='TamTruTamVang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_tttv', models.CharField(choices=[('Tạm trú', 'Tạm trú'), ('Tạm vắng', 'Tạm vắng')], max_length=20)),
                ('thoi_gian_bat_dau', models.TimeField()),
                ('thoi_gian_ket_thuc', models.TimeField()),
                ('ly_do', models.CharField(max_length=255)),
                ('dan_cu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.dancu')),
            ],
        ),
    ]
