# Generated by Django 5.2.1 on 2025-05-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamtrutamvang',
            name='thoi_gian_bat_dau',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tamtrutamvang',
            name='thoi_gian_ket_thuc',
            field=models.DateField(),
        ),
    ]
