# Generated by Django 5.0.7 on 2025-05-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0002_khoanthu_so_tien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogiadinh',
            name='id_chu_ho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chu_ho', to='apartment_management.dancu'),
        ),
    ]
