# Generated by Django 5.0.7 on 2025-05-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0002_alter_tamtrutamvang_thoi_gian_bat_dau_and_more'),
        ('apartment_management', '0003_alter_hogiadinh_id_chu_ho'),
    ]

    operations = [
    ]
