# Generated by Django 5.2.1 on 2025-05-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0004_merge_20250528_2200'),
        ('apartment_management', '0004_merge_20250528_2231'),
    ]

    operations = [
    ]
