# Generated by Django 5.2.1 on 2025-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0005_merge_20250528_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoanthu',
            name='loai_khoan_thu',
            field=models.CharField(choices=[('Bắt buộc', 'Bắt buộc'), ('Tự nguyện', 'Tự nguyện'), ('Cố định', 'Cố định')], max_length=20),
        ),
    ]
