# Generated by Django 5.2.1 on 2025-06-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0006_alter_khoanthu_loai_khoan_thu'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_bien_dong', models.CharField(choices=[('Chuyển đến', 'Chuyển đến'), ('Chuyển đi', 'Chuyển đi'), ('Tách hộ', 'Tách hộ')], max_length=20)),
                ('thoi_gian', models.DateField()),
                ('so_can_ho', models.IntegerField()),
                ('id_nhan_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.dancu')),
            ],
        ),
    ]
