# Generated by Django 5.2.1 on 2025-06-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0006_alter_khoanthu_loai_khoan_thu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoanthu',
            name='loai_khoan_thu',
            field=models.CharField(choices=[('Bắt buộc', 'Bắt buộc'), ('Tự nguyện', 'Tự nguyện'), ('Phương tiện', 'Phương tiện')], max_length=20),
        ),
    ]
