# Generated by Django 5.2.1 on 2025-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0007_biendong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biendong',
            name='loai_bien_dong',
            field=models.CharField(choices=[('Chuyển đến', 'Chuyển đến'), ('Chuyển đi', 'Chuyển đi')], max_length=20),
        ),
    ]
