# Generated by Django 5.2.1 on 2025-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0008_alter_biendong_loai_bien_dong'),
    ]

    operations = [
        migrations.AddField(
            model_name='biendong',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biendong',
            name='loai_bien_dong',
            field=models.CharField(choices=[('Chuyển đến', 'Chuyển đến'), ('Chuyển đi', 'Chuyển đi'), ('Qua đời', 'Qua đời')], max_length=20),
        ),
    ]
